name: ci

on:
  push:
    branches:
      - "**"
    paths:
      - "**.js"
      - "**.json"
      - "**/.mocharc.yaml"

jobs:
  runTests:
    uses: akromio/.github/.github/workflows/nodejs-pi-ci.yaml@master
