name: ci

on:
  workflow_dispatch:
  
  push:
    branches:
      - "**"
    paths:
      - "**.js"
      - "**.json"
      - "**/.mocharc.yaml"
      - .github/workflows/ci*.yaml

jobs:
  runTests:
    uses: akromio/.github/.github/workflows/nodejs-pi-ci.yaml@master
